---
# Main task

- name: Install ROS
  include: ros-install.yml
  tags: ros-install

- name: Workspaces Setup
  include: workspaces-setup.yml
  tags: workspaces-setup

- name: ROS Packages Install
  include: ros-packages-install.yml
  tags: ros-packages-install
